config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'services', to: 'static_pages#services'
  get 'get-started', to: 'static_pages#get_started'
  get 'about', to: 'static_pages#about'
  get 'hiring', to: 'static_pages#hiring'
  get 'testimonials', to: 'static_pages#testimonials'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def services
  end

  def get_started
  end

  def about
  end

  def hiring
  end

  def testimonials
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="page-ft">
  <!-- <div class="blocks blocks_2up"> -->
    <div class="box box_small">
        <div class="txt txt-center txt-md">
            <address>
              QuickAssist<br />
              Minneapolis, MN
            </address>
            <p>612-615-7795</p>
            <p>
              <a class="link" href="http://quickassistblog.com/contact/" target="_blank">
                  Contact us!
              </a>
            </p>
            <p>
                <a class="link" href="https://ws.onehub.com/signin" target="_blank">
                  Client Portal
                </a>
            </p>
        </div>
    </div>
    <div class="box box_small mix-box_no-top">
        <div class="txt txt-center txt-sm">
            <div class="txt-sm">If you need tax or CFO services, contact:</div>
              <a class="link" href="http://www.cpainthecloud.com" target="_blank">
                  cpainthecloud.com
              </a>
        </div>
    </div>
  <!-- </div> -->
</div>

app/views/layouts/_header.html.erb
<div class="page-hd mix-page-hd_static js-mainNavView" data-controller="js-stickyHeader">
    <ul class="mainNav-mobile">
        <li class="mainNav-mobile-item">
            <a class="link" href="<%= root_path %>">
                <img class="logo_mainNav" src="/assets/images/qa-logo-q_75x75.png" />
            </a>
        </li>
        <li class="mainNav-mobile-item">
          <a class="link" href="<%= services_path %>">
            Services
          </a>
        </li>
        <li class="mainNav-mobile-item">
          <a class="link" href="<%= get_started_path %>">
            Get Started
          </a>
        </li>
        <li class="mainNav-mobile-item">
          <a class="link" href="http://quickassistblog.com/" target="_blank">
            Blog
          </a>
        </li>
        <li class="mainNav-mobile-item">
          <a class="link" href="<%= about_path %>">
            About
          </a>
        </li>
        <!-- <li class="mainNav&#45;mobile&#45;item"> -->
        <!--   <a class="link" href="<%= testimonials_path %>"> -->
        <!--     Testimonials -->
        <!--   </a> -->
        <!-- </li> -->
        <li class="mainNav-mobile-item u-isHiddenSM">
          <div class="txt txt-sm txt-right mix-txt_primaryGrey">
            <address>
              QuickAssist<br />
              Minneapolis, MN
            </address>
            <p>612-615-7795</p>
            <p>
                <a class="link" href="http://quickassistblog.com/contact/" target="_blank">
                    Contact us!
                </a>
            </p>
            <p>
                <a class="link" href="https://ws.onehub.com/signin" target="_blank">
                  Client Portal
                </a>
            </p>
          </div>
        </li>
        <!--
        <li class="mainNav-mobile-item">
            <div class="trigger js-mobileNavTrigger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </li>
        -->
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>QuickAssist</title>

    <link rel="stylesheet" href="/assets/styles/modern.css">

    <%= csrf_meta_tags %>
</head>
<body>

    <div class="page" data-controller="js-app">
        <%= render 'layouts/header' %>

        <div class="page-bd">
            <%= yield %>
        </div>

        <%= render 'layouts/footer' %>
    </div>

    <script src=<% root_path %>"/assets/scripts/bundle.js"></script>
    <script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)
},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43564602-8', 'auto');
    ga('send', 'pageview');

    </script>
</body>
</html>

app/views/static_pages/_get_started_survey.html.erb
<div class="vr_8x js-surveyView">
  <div class="txt txt-center">
    <div class="vr_6x">
      <button class="btn btn_threeQuarters js-surveyTrigger">Let's get started!</button>
    </div>
    <iframe class="js-surveyFrame u-isVisuallyHidden" src="https://docs.google.com/forms/d/e/1FAIpQLSdub9lvmU0KlupnT6njAaHk6ESwp9ztlnJ3ZGt4hDI6atXkYg/viewform?embedded=true" width="760" height="2250" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
  </div>
</div>

app/views/static_pages/_priceLevels.html.erb
<ol class="priceLevel">
    <li>
      <div class="priceLevel-item" style="background: #888;">
          <div class="priceLevel-item-hd">
              <h3 class="hdg">Price level one</h3>
              <h4 class="hdg">prie level sub-heading</h4>
          </div>
          <div class="priceLevel-item-bd">
              <ol class="vlist mix-vlist_divided">
                  <li>item</li>
                  <li>item</li>
                  <li>item</li>
                  <li>item</li>
                  <li>item</li>
              </ol>
          </div>
          <div class="priceLevel-item-ft">
          </div>
        </div>
    </li>
    <li>
        <div class="priceLevel-item" style="background: #eee;">
            <div class="priceLevel-item-hd">
                <h3 class="hdg">Price level two</h3>
                <h4 class="hdg">prie level sub-heading</h4>
            </div>
            <div class="priceLevel-item-bd">
                <ol class="vlist mix-vlist_divided">
                    <li>item</li>
                    <li>item</li>
                    <li>item</li>
                    <li>item</li>
                    <li>item</li>
                </ol>
            </div>
            <div class="priceLevel-item-ft">
            </div>
        </div>
    </li>
    <li>
        <div class="priceLevel-item" style="background: #888;">
            <div class="priceLevel-item-hd">
                <h3 class="hdg">Price level three</h3>
                <h4 class="hdg">prie level sub-heading</h4>
            </div>
            <div class="priceLevel-item-bd">
                <ol class="vlist mix-vlist_divided">
                    <li>item</li>
                    <li>item</li>
                    <li>item</li>
                    <li>item</li>
                    <li>item</li>
                </ol>
            </div>
            <div class="priceLevel-item-ft">
            </div>
        </div>
    </li>
</ol>

app/views/static_pages/_teamMembers.html.erb
<div class="txt txt-center">
    <div class="vr_8x">
        <h2 class="hdg hdg_1">Meet the Team</h2>
    </div>
    <ul class="blocks blocks_2up" data-controller="js-biographyCard">
        <li>
            <a href="#">
              <img src="http://fillmurray.com/g/300/300" alt="Team Member"/>
              <br />
              {fname} {lname}
              <br />
              {title}
            </a>
        </li>
        <li>
            <a href="#">
              <img src="http://fillmurray.com/600/600" alt="Team Member"/>
              <br />
              {fname} {lname}
              <br />
              {title}
            </a>
        </li>
        <li>
            <a href="#">
              <img src="http://fillmurray.com/600/600" alt="Team Member"/>
              <br />
              {fname} {lname}
              <br />
              {title}
            </a>
        </li>
        <li>
            <a href="#">
              <img src="http://fillmurray.com/g/300/300" alt="Team Member"/>
              <br />
              {fname} {lname}
              <br />
              {title}
            </a>
        </li>
        <li>
            <a href="#">
              <img src="http://fillmurray.com/600/600" alt="Team Member"/>
              <br />
              {fname} {lname}
              <br />
              {title}
            </a>
        </li>

    </ul>
</div>

app/views/static_pages/about.html.erb
<div class="box box_medium box_narrow mix-box_255255255">
    <div class="txt txt-center">
        <div class="vr_8x">
            <h2 class="hdg hdg_1">About us</h2>
        </div>
        <div class="vr_6x">
          <img src="assets/images/stone-arch-bridge-minneapolis-mn.jpg" title="Stone Arch Bridge, Minneapolis, MN" />
        </div>
        <div class="vr_6x">
            <p class="txt txt-md mix-txt_primaryGrey">
              We are accountants and bookkeepers located in the heart of the Twin Cities.  We love getting to know our clients and their businesses and pride ourselves on giving our clients a personalized experience.  We constantly work to provide our clients with the best of current software in an effort to automate and streamline business and bookkeeping functions so you can concentrate on running your business.
            </p>
        </div>
        <div class="vr_6x">
          <p class="txt txt-md mix-txt_primaryGrey">
            We are number nerds!
          </p>
        </div>
        <div class="vr_6x">
          <a class="link txt-lg" href="http://dgeslin.com" target="_blank">
            Read our Blog
          </a>
        </div>
    </div>
</div>

app/views/static_pages/get_started.html.erb
<div class="box box_medium box_narrow mix-box_255255255">
  <div class="txt txt-center">
    <div class="vr_8x">
        <h2 class="hdg hdg_1">Sample Service Packages</h2>
    </div>
    <div class="vr_8x">
      <div class="priceTable">
        <div class="priceTablePlan">
          <div class="priceTablePlan-head">
            <h3 class="hdg hdg_3">Established</h3>
            <div class="priceTablePlan-price">
              $1,200 monthly
            </div>
            <div class="priceTablePlan-description">
              You’re big and bold and ready for anything.  But you’re tired of reconciling, paying bills and taking hours trying to figure out cash flow.  We’ll manage your books, pay your bills & sort out your revenue.
            </div>
          </div>
          <ul class="priceTablePlan-featureList">
            <li class="priceTablePlan-featureList-item">Weekly Reconciliation</li>
            <li class="priceTablePlan-featureList-item">Weekly Financials</li>
            <li class="priceTablePlan-featureList-item">Unlimited Support<br /> (Phone &amp; Email)</li>
            <li class="priceTablePlan-featureList-item">Quickbooks or Xero Account</li>
            <li class="priceTablePlan-featureList-item">Document Collection &amp; Storage</li>
            <li class="priceTablePlan-featureList-item">Slack Communication Channel</li>
            <li class="priceTablePlan-featureList-item">Electronic Bill Entry</li>
            <li class="priceTablePlan-featureList-item">Electronic Bill Pay</li>
          </ul>
          <h4 class="hdg hdg_4">Add On Services</h4>
          <ul class="priceTablePlan-featureList">
            <li class="priceTablePlan-featureList-item">Payroll</li>
            <li class="priceTablePlan-featureList-item">Invoicing</li>
            <li class="priceTablePlan-featureList-item">24hr Turnaround</li>
          </ul>
        </div>
        <div class="priceTablePlan priceTablePlan-mostPopular">
          <div class="priceTablePlan-head">
            <h3 class="hdg hdg_3">Growth</h3>
            <div class="priceTablePlan-price">
              $600 monthly
            </div>
            <div class="priceTablePlan-description">
              You’re ready to grow and need to delegate tasks to others.  Let us help you keep track of the finances so you can run the business.
            </div>
          </div>
          <ul class="priceTablePlan-featureList">
            <li class="priceTablePlan-featureList-item">Monthly Reconciliation</li>
            <li class="priceTablePlan-featureList-item">Monthly Financials</li>
            <li class="priceTablePlan-featureList-item">Unlimited Support<br /> (Phone &amp; Email)</li>
            <li class="priceTablePlan-featureList-item">Quickbooks or Xero Account</li>
            <li class="priceTablePlan-featureList-item">Document Collection &amp; Storage</li>
            <li class="priceTablePlan-featureList-item">Slack Communication Channel</li>
            <li class="priceTablePlan-featureList-item">Electronic Bill Entry</li>
          </ul>
          <h4 class="hdg hdg_4">Add On Services</h4>
          <ul class="priceTablePlan-featureList">
            <li class="priceTablePlan-featureList-item">Payroll</li>
            <li class="priceTablePlan-featureList-item">Invoicing</li>
          </ul>
        </div>
        <div class="priceTablePlan">
          <div class="priceTablePlan-head">
            <h3 class="hdg hdg_3">Start-up</h3>
            <div class="priceTablePlan-price">
              $250 monthly
            </div>
            <div class="priceTablePlan-description">
              You’re opening soon or have already opened and need a little help with the numbers.
            </div>
          </div>
          <ul class="priceTablePlan-featureList">
            <li class="priceTablePlan-featureList-item">Quarterly Reconciliation</li>
            <li class="priceTablePlan-featureList-item">Quarterly Financials</li>
            <li class="priceTablePlan-featureList-item">Unlimited Support<br /> (Phone &amp; Email)</li>
            <li class="priceTablePlan-featureList-item">Quickbooks or Xero Account</li>
          </ul>
          <h4 class="hdg hdg_4">Add On Services</h4>
          <ul class="priceTablePlan-featureList">
            <li class="priceTablePlan-featureList-item">Payroll</li>
          </ul>
        </div>
      </div>
    </div>

    <%= render 'static_pages/get_started_survey' %>
</div>

app/views/static_pages/hiring.html.erb
<div class="box box_medium box_narrow mix-box_255255255">
    <div class="txt txt-md txt-center">
        <div class="vr_6x">
            <h2 class="hdg hdg_1">We're Hiring</h2>
        </div>
        <div class="vr_6x">
            <p class="mix-txt_primaryGrey">
              We are always on the lookoout for qualified bookkeepers and CPAs who aren't afraid of learning new things and working on a variety of projects.  The ability to work in a variety of software programs and adapt to new processes and methods is a plus!  A fun and energetic personality would fit well with our current crew!.
            </p>
        </div>
    </div>
</div>

app/views/static_pages/home.html.erb
<div class="box box_small mix-box_jumbotron">
    <div class="section_media">
        <div class="section_media-img u-isHiddenSM">
            <img class="logo_cta" src="/assets/images/qa-logo-q.png" alt="logo" />
        </div>
        <div class="section_media-content">
            <div class="feature">
                <div class="feature-hd">
                  <h1>
                    <img src="/assets/images/qa-logo-script-white.png" alt="Qucik Assist" />
                  </h1>
                </div>
                <div class="feature-ft">
                  <h2 class="hdg hdg-tagline">
                    Innovative Bookkeeping Solutions
                  </h2>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="box box_medium mix-box_255255255 mix-box_divided">
    <div class="txt txt-center">
        <div class="vr_2x">
          <h2 class="hdg hdg_1">Meet OTIS</h2>
        </div>
        <div class="vr_6x">
          <div class="txt txt-lg mix-txt_primaryGrey">
            Using Cutting Edge Technologies to Simplify the Books and Records of your Business.
          </div>
        </div>
        <!-- <img src="/assets/images/meet&#45;otis&#45;quickassist.jpg" alt="Meet OTIS. Let him streamline your processes and increase clarity." /> -->
        <iframe width="560" height="315" src="https://www.youtube.com/embed/RD8_lNr0t4g?rel=0" frameborder="0" allowfullscreen></iframe>
    </div>
</div>

<div class="box box_medium mix-box_255255255">
    <div class="txt txt-center">
        <div class="vr_6x">
            <h2 class="hdg hdg_1">Clear Accounting in the Cloud</h2>
        </div>
        <div class="vr_8x">
            <div class="vr_4x">
                <p class="txt txt-lg mix-txt_primaryGrey">
                  Simplified Processes.  Increased Clarity.
                </p>
            </div>

            <div class="vr_4x">
                <p class="txt txt-md">
                    Using programs like <a class="link" href="https://qbo.intuit.com/redir/testdrive" target="_blank" name="Intuit Quickbooks Test Drive">Quickbooks</a>,
                    <a class="link" href="https://www.entryless.com/features" target="_blank" name="Entryless - Online bill transcription">Entryless</a>,
                    <a class="link" href="http://hubdoc.com/how-it-works" target="_blank" name="Hubdoc - How It Works">Hubdoc</a>,
                    <a class="link" href="https://www.bill.com/dhhome/" target="_blank" name="Bill.com">Bill.com</a>
                    and many others we help entrepreneurs manage their business through innovative technology.
                </p>
            </div>

            <p class="txt txt-md">
                <a class="link" href="http://quickassistblog.com/contact/" target="_blank">Contact us</a>
                today to see how we can help your business!
            </p>
        </div>
        <div class="box">
            <ul class="hlist hlist_loose">
            <li>
                <a href="http://proadvisor.intuit.com/quickbooks-help/david-j-geslin-2" target="_blank">
                    <img class="image image-constrained" src="/assets/images/quickbooks-online_logo_400-140.png" alt="Quickbooks Online" />
                </a>
            </li>
            <li>
                <a href="http://proadvisor.intuit.com/quickbooks-help/david-j-geslin-2" target="_blank">
                    <img class="image image-constrained" src="/assets/images/certification-quickbooks-icon.png" alt="Intuit Certified ProAdvisor" />
                </a>
            </li>
            <li>
              <a href="https://www.tsheets.com/#a:quickassist">
                <img src="//cdn.tsheets.com/images/rc_assets/PRO-badge.png" alt="Time tracking app for quickbooks" height="200px" />
              </a>
            </li>
            <li>
                <a href="http://www.hubdoc.com/?utm_source=partner" target="_blank">
                    <img src="http://blog.hubdoc.com/wp-content/uploads/2015/06/Bronze.png" width="125px" height="125px" border="0" alt="Hubdoc Bronze Partner" />
                </a>
            </li>
            <li>
                <a href="http://xero.com" target="_blank">
                    <img class="image image-constrained" src="/assets/images/xero-certified-advisor-logo-hires.png" alt="Xero Certified Advisor" />
                </a>
            </li>
        </ul>
        </div>
    </div>
</div>

app/views/static_pages/services.html.erb
<div class="box box_medium mix-box_255255255 mix-box_divided">
  <div class="vr_6x">
    <div class="vr_8x">
        <h2 class="hdg hdg_1 txt-center">We do the bookkeeping, you run your business</h2>
    </div>

    <div class="box box_narrow">
      <div class="blocks blocks_3up txt-center">
        <div>
          <a href="<%= services_path %>" title="">
            <img src="assets/images/quick-assist-many-hats-top-hat.png" alt="Accounts Payable" height="150px" />
          </a>
        </div>
        <div>
          <a href="<%= services_path %>" title="">
            <img src="assets/images/quick-assist-many-hats-chef-hat.png" alt="Bank Reconciliation" height="150px" />
          </a>
        </div>
        <div>
          <a href="<%= services_path %>" title="">
            <img src="assets/images/quick-assist-many-hats-fedora.png" alt="Payroll Processing" height="150px" />
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="vr_6x">
    <div class="box box_narrow">
      <div class="vr_4x">
        <p class="txt txt-left txt-lg">
            Being an entrepreneur requires you to wear many different hats
        </p>
      </div>
      <p class="txt txt-left txt-md">
        Instead of actually running your business, do you find yourself
        <ul class="vlist mix-vlist_unordered">
          <li>Paying and managing bills</li>
          <li>Entering sales figures</li>
          <li>Balancing your bank account</li>
          <li>Running payroll</li>
        </ul>
      </p>
    </div>
  </div>
  <div class="vr_8x">
    <div class="box box_narrow">
      <p class="txt txt-left">
        The burden of bookkeeping can be all consuming on the small business owner.  At Quick Assist, we help you get back to business at a fraction of the cost of an in-house bookkeeper.  With more knowledge and expertise, we can reconcile your accounts, issue invoices, track your accounts payable, pay your bills, and many other accounting tasks.
      </p>
    </div>
  </div>

  <div class="vr_6x">
    <div class="box box_narrow">
      <div class="blocks blocks_4up txt-center">
        <div>
          <a href="<%= services_path %>" title="">
            <img src="assets/images/quick-assist-calculator.png" alt="" />
          </a>
        </div>
        <div>
          <a href="<%= services_path %>" title="">
            <img src="assets/images/quick-assist-bank-reconciliation.png" alt="Bank Reconciliation" />
          </a>
        </div>
        <div>
          <a href="<%= services_path %>" title="">
            <img src="assets/images/quick-assist-pen.png" alt="Payroll Processing" />
          </a>
        </div>
        <div>
          <a href="<%= about_path %>" title="">
            <img src="assets/images/quick-assist-invoicing.png" alt="Invoicing" />
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="vr_8x">
    <div class="box box_narrow">
      <p class="txt txt-left">
        We work on a fixed fee basis so you always know your costs.  We offer unlimited consulting, free of charge, so you can get the answers you need to run your business without worrying about the billable hour.
      </p>
    </div>
  </div>

  <div class="vr_8x">
    <p class="txt txt-center">
      Let our experts take on the bookkeeping burden.<br />
      Contact us today!<br /><br />
      Phone: 612-615-7795<br />
      <a class="link" href="mailto:info@quickassist.biz" title="Contact us today!">info@quickassist.biz</a>
    </p>
  </div>

  <%= render 'static_pages/get_started_survey' %>
</div>

app/views/static_pages/testimonials.html.erb
<div class="box box_medium box_narrow mix-box_255255255">
  <div class="txt txt-center">
    <div class="vr_8x">
        <h2 class="hdg hdg_1">Testimonials</h2>
    </div>
    
</div>